{{- if .Values.provisioner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.provisioner.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: gcp-cni-provisioner
    {{- include "gcp-cni.labels" . | nindent 4 }}
  {{- with .Values.provisioner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
